stages:
  - lint

lint:
  stage: lint
  image: gradle:8.4.0-jdk21-jammy
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    # lint and compile projects
    - gradle build --console=plain --no-daemon
  cache:
    paths:
      - .gradle
